//! Settings › Diagnostics (SET-060, ENG-110, REL-002): log level (applies on restart; the
//! tracing filter is installed once at startup by `dk-hub`), *Open logs folder*, *Copy
//! diagnostics* (`hub.diagnostics()` → clipboard), per-engine transport (WSLC COM/CLI + WSL
//! version + fallback note), the version, and the third-party licences.
//!
//! Licences: `THIRD_PARTY_LICENSES.html` is embedded at build time and written to the data
//! directory through `hub.save_file` (no file I/O on the UI thread), then opened in the
//! default browser. The file is bundled with every package too (REL-002).

use gpui_kit::component::button::Button;
use gpui_kit::component::description_list::DescriptionList;
use gpui_kit::component::group_box::{GroupBox, GroupBoxVariants};
use gpui_kit::component::tag::Tag;
use gpui_kit::component::{ActiveTheme, IconName, Sizable, h_flex, v_flex};
use gpui_kit::prelude::*;
use gpui_kit::{AnyElement, App, ClipboardItem, Context, IntoElement, Window, div};

use super::SettingsPage;
use super::controls::Key;
use crate::actions::OpenLogsFolder;
use crate::actions::settings::{CopyDiagnostics, ViewLicenses};
use crate::state::AppState;
use crate::strings as s;
use crate::ui::notify;

/// The repo-root notices, regenerated by `cargo about` (REL-002).
pub const LICENSES_HTML: &str = include_str!("../../../../../THIRD_PARTY_LICENSES.html");
/// File name in the data directory.
pub const LICENSES_FILE: &str = "THIRD_PARTY_LICENSES.html";

/// *Copy diagnostics* (SET-060): `hub.diagnostics()` → clipboard + notification. The task is
/// fire-and-forget: it reports through a notification (CLAUDE.md "Store task handles").
pub fn copy_diagnostics(window: &mut Window, cx: &mut App) {
    let call = AppState::hub(cx).diagnostics();
    window
        .spawn(cx, async move |cx| {
            let r = call.await;
            cx.update(|window, cx| match r {
                Ok(text) => {
                    cx.write_to_clipboard(ClipboardItem::new_string(text));
                    notify::success(window, cx, s::DIAGNOSTICS_COPIED);
                }
                Err(e) => notify::engine_error(window, cx, s::DIAGNOSTICS_FAILED, &e),
            })
            .ok();
        })
        .detach();
}

/// *View licences* (REL-002): write the embedded notices to the data dir, then open them.
pub fn view_licenses(window: &mut Window, cx: &mut App) {
    let hub = AppState::hub(cx);
    let path = hub.paths().data_dir.join(LICENSES_FILE);
    let call = hub.save_file(
        path.clone(),
        bytes::Bytes::from_static(LICENSES_HTML.as_bytes()),
    );
    window
        .spawn(cx, async move |cx| {
            let r = call.await;
            cx.update(|window, cx| match r {
                Ok(()) => cx.open_with_system(&path),
                Err(e) => notify::engine_error(window, cx, s::LICENSES_FAILED, &e),
            })
            .ok();
        })
        .detach();
}

pub(super) fn blocks(
    this: &mut SettingsPage,
    _window: &mut Window,
    cx: &mut Context<SettingsPage>,
) -> Vec<AnyElement> {
    let hub = AppState::hub(cx);
    let log_dir = hub.paths().log_dir.display().to_string();
    let logging = GroupBox::new()
        .outline()
        .title(s::DIAG_LOGGING)
        .child(
            v_flex()
                .gap_3()
                .child(this.key_row(Key::LogLevel, s::DIAG_LOG_LEVEL, s::DIAG_LOG_LEVEL_DESC, cx))
                .child(super::setting_row(
                    s::DIAG_LOGS_FOLDER,
                    None,
                    h_flex()
                        .gap_2()
                        .items_center()
                        .child(
                            div()
                                .text_xs()
                                .font_family(cx.theme().mono_font_family.clone())
                                .text_color(cx.theme().muted_foreground)
                                .child(log_dir),
                        )
                        .child(
                            Button::new("diag-open-logs")
                                .small()
                                .outline()
                                .icon(IconName::FolderOpen)
                                .label(s::CMD_OPEN_LOGS_FOLDER)
                                .on_click(super::dispatch_here(&this.focus, OpenLogsFolder)),
                        )
                        .into_any_element(),
                    None,
                    cx,
                )),
        )
        .into_any_element();

    let support = GroupBox::new()
        .outline()
        .title(s::DIAG_SUPPORT)
        .child(super::setting_row(
            s::COPY_DIAGNOSTICS,
            Some(s::COPY_DIAGNOSTICS_DESC),
            Button::new("diag-copy")
                .small()
                .outline()
                .icon(IconName::Copy)
                .label(s::COPY_DIAGNOSTICS)
                .tooltip_with_action(s::COPY_DIAGNOSTICS, &CopyDiagnostics, None)
                .on_click(super::dispatch_here(&this.focus, CopyDiagnostics))
                .into_any_element(),
            None,
            cx,
        ))
        .into_any_element();

    // ENG-110: transport and WSL version per engine (connected at least once).
    let engines = this.engine_list.read(cx).engines().to_vec();
    let mut list = DescriptionList::horizontal().columns(1).bordered(true);
    for e in &engines {
        let value: AnyElement = match &e.info {
            Some(i) => h_flex()
                .gap_2()
                .items_center()
                .flex_wrap()
                .child(match &i.transport {
                    Some(t) => Tag::secondary()
                        .small()
                        .child(s::transport_label(t))
                        .into_any_element(),
                    None => div().into_any_element(),
                })
                .child(div().text_sm().child(s::engine_version(
                    &i.server_version,
                    i.api_version.as_deref(),
                    &i.os,
                    &i.arch,
                )))
                .when_some(i.transport_note.clone(), |this, n| {
                    this.child(Tag::info().small().child(n))
                })
                .into_any_element(),
            None => div()
                .text_sm()
                .text_color(cx.theme().muted_foreground)
                .child(s::DIAG_NOT_CONNECTED)
                .into_any_element(),
        };
        list = list.item(e.config.name.clone(), value, 1);
    }
    let transports = GroupBox::new()
        .outline()
        .title(s::DIAG_ENGINES)
        .child(if engines.is_empty() {
            div()
                .text_sm()
                .text_color(cx.theme().muted_foreground)
                .child(s::NO_ENGINES)
                .into_any_element()
        } else {
            list.into_any_element()
        })
        .into_any_element();

    let about = GroupBox::new()
        .outline()
        .title(s::DIAG_ABOUT)
        .child(
            v_flex()
                .gap_3()
                .child(super::setting_row(
                    s::DIAG_VERSION,
                    None,
                    div()
                        .text_sm()
                        .font_family(cx.theme().mono_font_family.clone())
                        .child(format!("{} {}", s::APP_NAME, env!("CARGO_PKG_VERSION")))
                        .into_any_element(),
                    None,
                    cx,
                ))
                .child(super::setting_row(
                    s::VIEW_LICENSES,
                    Some(s::VIEW_LICENSES_DESC),
                    Button::new("diag-licenses")
                        .small()
                        .outline()
                        .icon(IconName::ExternalLink)
                        .label(s::VIEW_LICENSES)
                        .on_click(super::dispatch_here(&this.focus, ViewLicenses))
                        .into_any_element(),
                    None,
                    cx,
                )),
        )
        .into_any_element();

    vec![logging, support, transports, about]
}
